### ISSUE TITLE
Rename the project ionic-force (pretty please :-))

### ISSUE THREAD

**Issue by anupj** [driftyco/ionic-starter-salesforce#14]
Hey guys, Not really a bug but a humble request really. Whilst ionic-starter-salesforce is a great name for this project I was wondering if you would consider using ionic-force (or perhaps ion-force) since most of salesforce modules/projects for other frameworks are named in a similar fashion (ng-force [angularjs salesforce module], nforce [node.js wrapper for salesforce] etc.).

Please note I am not a salesforce employee. It was just a thought since most the salesforce-external frameworks projects follow this convention. Feel free to ignore it. kthanxbai! :-) 

Anup

**Comment by mlynch** [comment]
That's really a question for @ccoenraets
